language: python

# command to install dependencies
install:
  - pip install --only-binary=scipy
  - pip install -r requirements.txt
  - python setup.py -q install

# command to run tests
script: pytest